# Primary DC2->DC1 link (dc-gw-3 <-> dc-gw-1): export imported remote routes only.
apiVersion: routingpolicies.eda.nokia.com/v1
kind: Policy
metadata:
  name: export-wan-routes-only-dc-2
  namespace: clab-3-tier-leaf-spine-dcgw
  annotations:
    l2: loop-avoidance
  labels:
    eda.nokia.com/dci: evpn-wan
    eda.nokia.com/platform: sros
spec:
  defaultAction:
    policyResult: Accept
  statements:
    - name: reject-local-evpn
      action:
        policyResult: Reject
      match:
        families:
          - EVPN
        tags:
          tagSet: tag-20
    - name: reject-local-bgp-vpn
      action:
        policyResult: Reject
      match:
        protocol: BGP_VPN
        families:
          - IPv4
        tags:
          tagSet: tag-20
